#if !canImport(ObjectiveC)
    import XCTest

    extension EOSIOKeyEncryptionTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__EOSIOKeyEncryptionTests = [
            ("testEncryption", testEncryption),
            ("testSecurityLevel", testSecurityLevel),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(EOSIOKeyEncryptionTests.__allTests__EOSIOKeyEncryptionTests),
        ]
    }
#endif
